import AddBanner from "@/components/views/banners/banner";
import Head from "next/head";
Banners.layout = "dashboard";
export default function Banners() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AddBanner />
    </div>
  );
}
