import { Button } from "antd";
import Head from "next/head";
import Image from "next/image";

Home.layout = "main";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h2>Home Page</h2>
      <Button>hello</Button>
    </div>
  );
}
